#spring.application.name=SpringBootandSpringDataJPA
#
#logging.level.org.springframework=debug


logging:
  level:
    org:
      springframework: debug



spring: 
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootjpaapplication
    username: postgres
    password: Srt@12022001
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
